name: Auto Approve and merge paketo-bot PR

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'run-receipt'
      - 'build-receipt'
      - '.github/workflows/ci-artifacts/**'

jobs:
  approve:
    name: Auto Approve
    if: ${{ github.event.pull_request.user.login == 'paketo-bot' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Approve
        uses: paketo-buildpacks/github-config/actions/pull-request/approve@main
        with:
          token: ${{ secrets.PAKETO_BOT_REVIEWER_GITHUB_TOKEN }}
          number: ${{ github.event.number }}

  automerge:
    name: Merge or Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Pull Request Details
        id: pull_request
        env:
          NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        run: |
          payload="$(
            curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${NUMBER}" \
              --silent \
              --location \
              --header "Authorization: token ${GITHUB_TOKEN}"
          )"
          echo "::set-output name=mergeable_state::$(echo "${payload}" | jq -r -c .mergeable_state)"

      - name: Merge
        if: ${{ steps.pull_request.outputs.mergeable_state == 'clean' || steps.pull_request.outputs.mergeable_state == 'unstable' }}
        uses: paketo-buildpacks/github-config/actions/pull-request/merge@main
        with:
          token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
          number: ${{ github.event.number }}

      - name: Rebase
        if: ${{ steps.pull_request.outputs.mergeable_state == 'behind' }}
        uses: paketo-buildpacks/github-config/actions/pull-request/rebase@main
        with:
          token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
          number: ${{ github.event.number }}