name: Build and Test Stack

on:
  workflow_dispatch: { }
  schedule:
    # Every Sunday at 1:00 AM
    - cron: '0 1 * * 0'
  push:
    branches: [ main ]
    paths:
      - 'usns'

jobs:
  build-and-test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Checkout Branch
        uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
        with:
          branch: automation/receipts/update

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Docker login
        run: |
          docker login -u ${{ secrets.PAKETO_TESTING_DOCKERHUB_USERNAME }} --password-stdin \
            < <(echo '${{ secrets.PAKETO_TESTING_DOCKERHUB_PASSWORD }}')

      - name: Build and push images
        id: build-images
        uses: paketo-buildpacks/stacks/actions/create-stack@main
        with:
          build_destination: paketotesting/build-rc
          run_destination: paketotesting/run-rc
          version: ${{ github.sha }}
          stack: tiny
          publish: true

      - name: Test stack
        uses: paketo-buildpacks/stacks/actions/test-stack@main
        with:
          stack_id: 'io.buildpacks.stacks.bionic'
          build_cnb_image: ${{ steps.build-images.outputs.build_cnb_sha }}
          run_cnb_image: ${{ steps.build-images.outputs.run_cnb_sha }}

      - name: Generate build image receipt
        run: |
          docker pull "${BUILD_CNB_IMAGE}"
          docker run "${BUILD_CNB_IMAGE}" dpkg -l > build-receipt

          echo "${BUILD_BASE_IMAGE}" > build-base-image
          echo "${BUILD_CNB_IMAGE}" > build-cnb-image
          echo "${BUILD_BASE_IMAGE_TAG}" > build-base-image-tag
          echo "${RUN_BASE_IMAGE}" > run-base-image
          echo "${RUN_CNB_IMAGE}" > run-cnb-image

      - name: Generate run image receipt
        run: |
          docker pull "${RUN_CNB_IMAGE}"
          container_id="$(docker create "${RUN_CNB_IMAGE}" sleep)"
          docker cp "${container_id}":/var/lib/dpkg/status.d /tmp/tiny-pkgs
          docker rm -v "${container_id}"

          cat > run-receipt << EOF
                         Name                              Version                            Architecture
          +++-===================================-===================================-===================================
          EOF

          for pkg in /tmp/tiny-pkgs/*; do
          name="$(cat "${pkg}" | grep ^Package: | cut -d ' ' -f2)"
          version="$(cat "${pkg}" | grep ^Version: | cut -d ' ' -f2)"
          arch="$(cat "${pkg}" | grep ^Architecture: | cut -d ' ' -f2)"

          printf "ii  %-35s %-35s %-35s\n" ${name} ${version} ${arch} >> run-receipt
          done

      - name: Check changes
        id: check-receipts
        run: |
          if [[ "$(git diff -s --exit-code build-receipt run-receipt && echo $?)" ]]; then
            echo "::set-output name=receipts-diffs::false"
          else
            echo "::set-output name=receipts-diffs::true"
          fi

      - name: Update image files
        if: ${{ steps.check-receipts.outputs.receipts-diffs == true }}
        run: |
          echo ${{ steps.build-images.outputs.build_base_sha }} > .github/ci-artifacts/build-base-image
          echo ${{ steps.build-images.outputs.build_cnb_sha }} > .github/ci-artifacts/build-cnb-image
          echo ${{ steps.build-images.outputs.run_base_sha }} > .github/ci-artifacts/run-base-image
          echo ${{ steps.build-images.outputs.run_cnb_sha }} > .github/ci-artifacts/run-cnb-image

      - name: Commit
        if: ${{ steps.check-receipts.outputs.receipts-diffs == true }}
        id: commit
        uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
        with:
          message: "Update receipts"
          pathspec: "."

      - name: Push Branch
        if: ${{ steps.check-receipts.outputs.receipts-diffs == true }}
        uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
        with:
          branch: automation/receipts/update

      - name: Open Pull Request
        if: ${{ steps.check-receipts.outputs.receipts-diffs == true }}
        uses: paketo-buildpacks/github-config/actions/pull-request/open@main
        with:
          token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
          title: "Update receipts"
          branch: automation/receipts/update
