name: Commit Receipts
on:
  repository_dispatch:
    types: [ new-stack-rc ]
  workflow_dispatch:
    inputs:
      RUN_BASE_IMAGE:
        required: true
      RUN_CNB_IMAGE:
        required: true
      BUILD_BASE_IMAGE:
        required: true
      BUILD_CNB_IMAGE:
        required: true
      BUILD_BASE_IMAGE_TAG:
        required: false

env:
  RUN_BASE_IMAGE: ${{ github.event.client_payload.run_base_image }}
  RUN_CNB_IMAGE: ${{ github.event.client_payload.run_cnb_image }}
  BUILD_BASE_IMAGE: ${{ github.event.client_payload.build_base_image }}
  BUILD_CNB_IMAGE: ${{ github.event.client_payload.build_cnb_image }}
  BUILD_BASE_IMAGE_TAG: ${{ github.event.client_payload.build_base_image_tag }}

jobs:
  commit-receipts:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout Branch
      uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
      with:
        branch: automation/receipts/update

    - name: Set Env Vars
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "RUN_BASE_IMAGE=${{ github.event.inputs.RUN_BASE_IMAGE }}" >> $GITHUB_ENV
          echo "RUN_CNB_IMAGE=${{ github.event.inputs.RUN_CNB_IMAGE }}" >> $GITHUB_ENV
          echo "BUILD_BASE_IMAGE=${{ github.event.inputs.BUILD_BASE_IMAGE }}" >> $GITHUB_ENV
          echo "BUILD_CNB_IMAGE=${{ github.event.inputs.BUILD_CNB_IMAGE }}" >> $GITHUB_ENV
          echo "BUILD_BASE_IMAGE_TAG=${{ github.event.inputs.BUILD_BASE_IMAGE_TAG }}" >> $GITHUB_ENV
        fi

    - name: Docker login
      run: |
        docker login -u ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }} --password-stdin \
          < <(echo "${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}")

    - name: Generate build image receipt
      run: |
        docker pull "${BUILD_CNB_IMAGE}"
        docker run "${BUILD_CNB_IMAGE}" dpkg -l > build-receipt

        echo "${BUILD_BASE_IMAGE}" > build-base-image
        echo "${BUILD_CNB_IMAGE}" > build-cnb-image
        echo "${BUILD_BASE_IMAGE_TAG}" > build-base-image-tag
        echo "${RUN_BASE_IMAGE}" > run-base-image
        echo "${RUN_CNB_IMAGE}" > run-cnb-image

    - name: Generate run image receipt
      run: |
        docker pull "${RUN_CNB_IMAGE}"
        container_id="$(docker create "${RUN_CNB_IMAGE}" sleep)"
        docker cp "${container_id}":/var/lib/dpkg/status.d /tmp/tiny-pkgs
        docker rm -v "${container_id}"

        cat > run-receipt << EOF
                          Name                              Version                            Architecture
        +++-===================================-===================================-===================================
        EOF

        for pkg in /tmp/tiny-pkgs/*; do
          name="$(cat "${pkg}" | grep ^Package: | cut -d ' ' -f2)"
          version="$(cat "${pkg}" | grep ^Version: | cut -d ' ' -f2)"
          arch="$(cat "${pkg}" | grep ^Architecture: | cut -d ' ' -f2)"

          printf "ii  %-35s %-35s %-35s\n" ${name} ${version} ${arch} >> run-receipt
        done

    - name: Commit
      id: commit
      uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
      with:
        message: "Update receipts and images"
        pathspec: "."

    - name: Push Branch
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
      with:
        branch: automation/receipts/update

    - name: Open Pull Request
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/open@main
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        title: "Update receipts"
        branch: automation/receipts/update
