name: Create Release
on:
  repository_dispatch:
    types: [receipt-update]
  workflow_dispatch:
    inputs:
      TAG:
        required: true
      BUILD_BASE_IMAGE_TAG:
        required: true

env:
  BUILD_REPO: "paketobuildpacks/build"
  RUN_REPO: "paketobuildpacks/run"
  TAG: ${{ github.event.client_payload.tag }}
  BUILD_BASE_IMAGE_TAG: ${{ github.event.client_payload.build_base_image_tag }}

jobs:
  create-release:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout Branch
      uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
      with:
        branch: automation/usns/release    

    - name: Set Env Vars
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "TAG=${{ github.event.inputs.TAG }}" >> $GITHUB_ENV
          echo "BUILD_BASE_IMAGE_TAG=${{ github.event.inputs.BUILD_BASE_IMAGE_TAG }}" >> $GITHUB_ENV
        fi

    - name: Docker login
      run: |
        docker login -u ${{ secrets.PAKETO_BUILDPACKS_DOCKER_USER }} --password-stdin \
          < <(echo "${{ secrets.PAKETO_BUILDPACKS_DOCKER_PASS }}")

    - name: Get Image Refs
      id: image-refs
      shell: bash --noprofile --norc -eo pipefail {0}
      run: |
        run_base_sha="$(skopeo inspect "docker://${RUN_REPO}:${TAG}-tiny" | jq .Digest -r)"
        run_cnb_sha="$(skopeo inspect "docker://${RUN_REPO}:${TAG}-tiny-cnb" | jq .Digest -r)"
        build_base_sha="$(skopeo inspect "docker://${BUILD_REPO}:${{ env.BUILD_BASE_IMAGE_TAG }}" | jq .Digest -r)"
        build_cnb_sha="$(skopeo inspect "docker://${BUILD_REPO}:${TAG}-tiny-cnb" | jq .Digest -r)"

        echo "::set-output name=run_base_sha::${run_base_sha}"
        echo "::set-output name=run_cnb_sha::${run_cnb_sha}"
        echo "::set-output name=build_base_sha::${build_base_sha}"
        echo "::set-output name=build_cnb_sha::${build_cnb_sha}"

    - name: Generate receipt diffs
      id: receipt
      uses: paketo-buildpacks/stacks/actions/receipt-diff@main
      with:
        repo: ${{ github.repository }}
        user: core-deps-ci-bot
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

    - name: Get USN List
      id: get-usns
      run: |
        curl -sL --fail -u 'paketo-bot:${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}' \
          api.github.com/repos/paketo-buildpacks/stack-usns/contents/usns | \
          jq -r '.content' | base64 --decode > full-usn-list
        echo "::set-output name=usn_path::full-usn-list"

    - name: Create Release Notes
      id: create-release-notes
      uses: paketo-buildpacks/stacks/actions/release-notes@main
      with:
        build_base_image: "${{ env.BUILD_REPO }}@${{ steps.image-refs.outputs.build_base_sha }}"
        build_base_image_tag: "${{ env.BUILD_REPO }}:${{ env.BUILD_BASE_IMAGE_TAG }}"
        build_cnb_image: "${{ env.BUILD_REPO }}@${{ steps.image-refs.outputs.build_cnb_sha }}"
        run_cnb_image: "${{ env.RUN_REPO }}@${{ steps.image-refs.outputs.run_cnb_sha }}"
        run_base_image: "${{ env.RUN_REPO }}@${{ steps.image-refs.outputs.run_base_sha }}"
        build_receipt_diff: ${{ steps.receipt.outputs.build_diff }}
        run_receipt_diff: ${{ steps.receipt.outputs.run_diff }}
        relevant_usns: usns
        all_usns: ${{ steps.get-usns.outputs.usn_path }}
        release_version: ${{ env.TAG }}
        stack: tiny

    - name: Create Release
      uses: paketo-buildpacks/github-config/actions/release/create@main
      with:
        repo: ${{ github.repository }}
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        tag_name: ${{ env.TAG }}
        target_commitish: ${{ github.sha }}
        name: ${{ env.TAG }}
        body: ${{ steps.create-release-notes.outputs.release_body }}
        draft: false

    - name: Commit
      id: commit
      uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
      with:
        message: "Update USNs"
        pathspec: "usns"

    - name: Push Branch
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
      with:
        branch: automation/usns/release

    - name: Open Pull Request
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/open@main
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        title: "Update USNs"
        branch: automation/usns/release